// DO NOT MODIFY ! DO NOT MODIFY ! DO NOT MODIFY ! DO NOT MODIFY ! DO NOT MODIFY
// xrb_parse_datafile_parser.cpp generated by trison
// from xrb_parse_datafile_parser.trison using trison.cpp.targetspec and trison.cpp.implementation.codespec
// DO NOT MODIFY ! DO NOT MODIFY ! DO NOT MODIFY ! DO NOT MODIFY ! DO NOT MODIFY

#include "xrb_parse_datafile_parser.hpp"


#define TRISON_CPP_DEBUG_CODE_(spew_code) if (DebugSpew()) { spew_code; }


#line 78 "xrb_parse_datafile_parser.trison"

#include <sstream>

#include "xrb_emptystring.hpp"
#include "xrb_parse_datafile_scanner.hpp"
#include "xrb_parse_datafile_value.hpp"

#undef FL
#define FL (m_scanner->GetFiLoc())

namespace Xrb {
namespace Parse {
namespace DataFile {

Parser::ReturnCode Parser::Parse (std::string const &input_path)
{
    ASSERT1(m_scanner != NULL);
    ASSERT1(!m_scanner->IsOpen());

    // if there are any pipe characters in the path, return failure
    if (input_path.find_first_of("|") != static_cast<std::string::size_type>(-1))
        return RC_INVALID_FILENAME;

    // attempt to open the path and return the result
    if (!m_scanner->Open(input_path))
        return RC_FILE_OPEN_FAILURE;

    // start parsing, and return parse error if we got an unhandled error
    if (Parse(&m_accepted_value) != PRC_SUCCESS)
        return RC_PARSE_ERROR;

    // if any errors were encountered, return parse error
    if (m_scanner->ErrorsWereEncountered())
        return RC_ERRORS_ENCOUNTERED;

    // otherwise return success
    return RC_SUCCESS;
}

void Parser::EmitWarning (std::string const &message, FiLoc const &filoc)
{
    ASSERT1(m_scanner != NULL);
    m_scanner->EmitWarning(message, filoc);
}

void Parser::EmitError (std::string const &message, FiLoc const &filoc)
{
    ASSERT1(m_scanner != NULL);
    m_scanner->EmitError(message, filoc);
}

#line 65 "xrb_parse_datafile_parser.cpp"

Parser::Parser ()
{
    DebugSpew(false);


#line 129 "xrb_parse_datafile_parser.trison"

//     DebugSpew(true);
    m_scanner = new Scanner();
    m_accepted_value = NULL;

#line 78 "xrb_parse_datafile_parser.cpp"
}

Parser::~Parser ()
{
    // clean up dynamically allocated memory.
    ClearStack_();
    ClearLookaheadQueue_();



#line 134 "xrb_parse_datafile_parser.trison"

    ASSERT1(m_scanner != NULL);
    Delete(m_scanner);
    delete StealAcceptedStructure();

#line 95 "xrb_parse_datafile_parser.cpp"
}

bool Parser::IsAtEndOfInput ()
{
    return Lookahead_(0).m_id == Terminal::END_;
}

void Parser::ResetForNewInput ()
{
    TRISON_CPP_DEBUG_CODE_(std::cerr << 
#line 165 "xrb_parse_datafile_parser.trison"
"DataFile::Parser" << (m_scanner->GetFiLoc().IsValid() ? " ("+m_scanner->GetFiLoc().AsString()+")" : g_empty_string) << ":"
#line 108 "xrb_parse_datafile_parser.cpp"
 << " executing reset-for-new-input actions" << std::endl)

    // clean up stuff that might be hanging around from the last parse's input.
    ClearStack_();
    ClearLookaheadQueue_();
}

Parser::ParserReturnCode Parser::Parse (Value * *return_token, ParseNonterminal::Name nonterminal_to_parse)
{

#line 139 "xrb_parse_datafile_parser.trison"

    delete StealAcceptedStructure();

#line 123 "xrb_parse_datafile_parser.cpp"

    ParserReturnCode const parse_return_code = Parse_(return_token, nonterminal_to_parse);


#line 142 "xrb_parse_datafile_parser.trison"

    m_scanner->Close();

#line 132 "xrb_parse_datafile_parser.cpp"

    return parse_return_code;
}

// ///////////////////////////////////////////////////////////////////////
// begin internal trison-generated parser guts -- don't use
// ///////////////////////////////////////////////////////////////////////

Parser::ParserReturnCode Parser::Parse_ (Value * *return_token, ParseNonterminal::Name nonterminal_to_parse)
{
    assert(return_token != NULL && "the return-token pointer must be non-NULL");

    TRISON_CPP_DEBUG_CODE_(std::cerr << 
#line 165 "xrb_parse_datafile_parser.trison"
"DataFile::Parser" << (m_scanner->GetFiLoc().IsValid() ? " ("+m_scanner->GetFiLoc().AsString()+")" : g_empty_string) << ":"
#line 148 "xrb_parse_datafile_parser.cpp"
 << " starting parse" << std::endl)

    ParserReturnCode parser_return_code_ = PRC_UNHANDLED_PARSE_ERROR;
    *return_token = NULL;

    // make sure all our structures are empty and variables initialized.
    // we don't clear the lookahead queue here because we might want to
    // parse multiple times from the same input, and the lookahead queue
    // could have the next few tokens in it.
    ClearStack_();
    m_is_in_error_panic_ = false;

    // push the initial state of the DPDA.
    assert((false
           || nonterminal_to_parse == ParseNonterminal::array
           || nonterminal_to_parse == ParseNonterminal::data_file
           || nonterminal_to_parse == ParseNonterminal::element
           || nonterminal_to_parse == ParseNonterminal::element_list
           || nonterminal_to_parse == ParseNonterminal::string
           || nonterminal_to_parse == ParseNonterminal::structure
           || nonterminal_to_parse == ParseNonterminal::value
           || nonterminal_to_parse == ParseNonterminal::value_list
           ) && "invalid nonterminal_to_parse");
    m_stack_.push_back(StackElement_(nonterminal_to_parse, NULL));
    // main parser loop
    while (true)
    {
        if (m_is_in_error_panic_)
        {
            TRISON_CPP_DEBUG_CODE_(std::cerr << 
#line 165 "xrb_parse_datafile_parser.trison"
"DataFile::Parser" << (m_scanner->GetFiLoc().IsValid() ? " ("+m_scanner->GetFiLoc().AsString()+")" : g_empty_string) << ":"
#line 181 "xrb_parse_datafile_parser.cpp"
 << " begin error panic" << std::endl)

            while (true)
            {
                // get the current state (top of the stack)
                assert(!m_stack_.empty());
                BarfCpp_::Uint32 current_state_index = m_stack_.rbegin()->m_state_index;
                assert(current_state_index < ms_state_count_);
                State_ const &current_state = ms_state_table_[current_state_index];
                TRISON_CPP_DEBUG_CODE_(PrintParserStatus_(std::cerr))

                // check if the current state accepts ERROR_ (only need to check the
                // non-default transitions, since the default transition can't be a shift).
                bool accepts_error = false;
                for (Transition_ const *transition = current_state.m_transition_table+1, // +1 because the first is the default
                                       *transition_end = current_state.m_transition_table+current_state.m_transition_count;
                     transition != transition_end;
                     ++transition)
                {
                    if (transition->m_type == Transition_::SHIFT && transition->m_lookahead_count == 1 && *transition->m_lookahead_sequence == Terminal::ERROR_)
                    {
                        accepts_error = true;
                        break;
                    }
                }

                if (accepts_error)
                {
                    TRISON_CPP_DEBUG_CODE_(std::cerr << 
#line 165 "xrb_parse_datafile_parser.trison"
"DataFile::Parser" << (m_scanner->GetFiLoc().IsValid() ? " ("+m_scanner->GetFiLoc().AsString()+")" : g_empty_string) << ":"
#line 213 "xrb_parse_datafile_parser.cpp"
 << " end error panic; success (current state accepts ERROR_ token)" << std::endl)
                    // if the current state accepts error, then we check if the lookahead token
                    // is Terminal::END_.  if it is, then we add a dummy Terminal::ERROR_ token
                    // in before it (since %error can't accept END_).  otherwise, we throw away
                    // the lookahead token, then clear the thrown-away token data, and set the
                    // token id to ERROR_.
                    assert(!m_lookahead_queue_.empty());
                    if (m_lookahead_queue_[0].m_id == Terminal::END_)
                    {
                        TRISON_CPP_DEBUG_CODE_(std::cerr << 
#line 165 "xrb_parse_datafile_parser.trison"
"DataFile::Parser" << (m_scanner->GetFiLoc().IsValid() ? " ("+m_scanner->GetFiLoc().AsString()+")" : g_empty_string) << ":"
#line 226 "xrb_parse_datafile_parser.cpp"
 << " deferring Terminal::END_ (padding with Terminal::ERROR_ token)" << std::endl)
                        m_lookahead_queue_.push_front(Token(Terminal::END_)); // dummy value
                    }
                    else
                        ThrowAwayToken_(m_lookahead_queue_[0].m_data);
                    m_lookahead_queue_[0].m_id = Terminal::ERROR_;
                    m_lookahead_queue_[0].m_data = NULL;
                    m_is_in_error_panic_ = false;
                    break;
                }
                else
                {
                    if (m_stack_.size() > 1)
                    {
                        TRISON_CPP_DEBUG_CODE_(std::cerr << 
#line 165 "xrb_parse_datafile_parser.trison"
"DataFile::Parser" << (m_scanner->GetFiLoc().IsValid() ? " ("+m_scanner->GetFiLoc().AsString()+")" : g_empty_string) << ":"
#line 244 "xrb_parse_datafile_parser.cpp"
 << " continue error panic; pop stack (current state doesn't accept ERROR_ token)" << std::endl)
                    }
                    else
                    {
                        TRISON_CPP_DEBUG_CODE_(std::cerr << 
#line 165 "xrb_parse_datafile_parser.trison"
"DataFile::Parser" << (m_scanner->GetFiLoc().IsValid() ? " ("+m_scanner->GetFiLoc().AsString()+")" : g_empty_string) << ":"
#line 252 "xrb_parse_datafile_parser.cpp"
 << " end error panic; abort (stack is empty)" << std::endl)
                    }
                    // otherwise throw away the data at the top of the stack, and pop the stack.
                    // then if the stack is empty, an unhandled parse error occurred.
                    ThrowAwayToken_(m_stack_.rbegin()->m_token_data);
                    m_stack_.resize(m_stack_.size()-1);
                    if (m_stack_.empty())
                    {
                        // parser_return_code_ and return_token are already appropriately
                        // set, so just break out of the inner loop.
                        break;
                    }
                }
            }

            // if we're still in error panic, then this indicates that we bottomed-
            // out the stack and it's an unhandled parse error, so break from the
            // main loop.
            if (m_is_in_error_panic_)
                break;
        }
        else // !m_is_in_error_panic_
        {
            // get the current state (top of the stack)
            assert(!m_stack_.empty());
            BarfCpp_::Uint32 current_state_index = m_stack_.rbegin()->m_state_index;
            assert(current_state_index < ms_state_count_);
            State_ const &current_state = ms_state_table_[current_state_index];
            TRISON_CPP_DEBUG_CODE_(PrintParserStatus_(std::cerr))

            // TODO -- binary search for faster transition matching?

            // loop through the current state's transitions and see if any match
            bool transition_exercised = false;
            BarfCpp_::Uint32 tested_lookahead_count = 0;
            for (Transition_ const *transition = current_state.m_transition_table+1, // +1 because the first is the default
                                   *transition_end = current_state.m_transition_table+current_state.m_transition_count;
                transition != transition_end;
                ++transition)
            {
                // the non-default transitions can only be REDUCE or SHIFT
                assert(transition->m_type == Transition_::REDUCE || transition->m_type == Transition_::SHIFT);

                // check if the lookaheads match those of this transition.
                bool lookahead_sequence_matched = true;
                for (BarfCpp_::Uint32 i = 0; i < transition->m_lookahead_count; ++i)
                {
                    if (Lookahead_(i).m_id != transition->m_lookahead_sequence[i])
                    {
                        lookahead_sequence_matched = false;
                        break;
                    }
                    else
                    {
                        if (i+1 > tested_lookahead_count)
                            tested_lookahead_count = i+1;
                    }
                }

                // if all the lookaheads matched, then exercise this transition,
                // and break out of this inner (transition) loop.
                if (lookahead_sequence_matched)
                {
                    TRISON_CPP_DEBUG_CODE_(std::cerr << 
#line 165 "xrb_parse_datafile_parser.trison"
"DataFile::Parser" << (m_scanner->GetFiLoc().IsValid() ? " ("+m_scanner->GetFiLoc().AsString()+")" : g_empty_string) << ":"
#line 319 "xrb_parse_datafile_parser.cpp"
 << " current (relevant) lookahead(s):")
                    for (BarfCpp_::Uint32 i = 0; i < tested_lookahead_count; ++i)
                    {
                        TRISON_CPP_DEBUG_CODE_(std::cerr << ' ' << Lookahead_(i))
                    }
                    TRISON_CPP_DEBUG_CODE_(std::cerr << std::endl)

                    ExerciseTransition_(*transition);
                    transition_exercised = true;
                    break;
                }
            }

            // if no transition was exercised, then exercise the default transition
            if (!transition_exercised)
            {
                TRISON_CPP_DEBUG_CODE_(std::cerr << 
#line 165 "xrb_parse_datafile_parser.trison"
"DataFile::Parser" << (m_scanner->GetFiLoc().IsValid() ? " ("+m_scanner->GetFiLoc().AsString()+")" : g_empty_string) << ":"
#line 339 "xrb_parse_datafile_parser.cpp"
 << " current (relevant) lookahead(s):")
                for (BarfCpp_::Uint32 i = 0; i < tested_lookahead_count; ++i)
                {
                    TRISON_CPP_DEBUG_CODE_(std::cerr << ' ' << Lookahead_(i))
                }
                TRISON_CPP_DEBUG_CODE_(std::cerr << std::endl)

                TRISON_CPP_DEBUG_CODE_(std::cerr << 
#line 165 "xrb_parse_datafile_parser.trison"
"DataFile::Parser" << (m_scanner->GetFiLoc().IsValid() ? " ("+m_scanner->GetFiLoc().AsString()+")" : g_empty_string) << ":"
#line 350 "xrb_parse_datafile_parser.cpp"
 << " exercising default transition" << std::endl)
                // exercise the default transition.  a return value of true indicates
                // that the parser should return.
                if (ExerciseTransition_(*current_state.m_transition_table))
                {
                    // the token (data) on the top of the stack is the return token.
                    // set parser_return_code_ and assign the top stack token data to
                    // *return_token and then break out of the main parser loop.
                    assert(m_stack_[0].m_state_index == BarfCpp_::Uint32(nonterminal_to_parse));
                    assert(m_stack_.size() == 2);
                    parser_return_code_ = PRC_SUCCESS;
                    *return_token = m_stack_.rbegin()->m_token_data;
                    // take the return token out of the stack, so it's not thrown away
                    // when we clear the stack later.
                    m_stack_.rbegin()->m_token_data = NULL;
                    break;
                }
            }
        }
    }

    // clear the stack, because we won't need it for the next parse.
    // we don't clear the lookahead queue here because we might want to
    // parse multiple times from the same input, and the lookahead queue
    // could have the next few tokens in it.
    ClearStack_();

    TRISON_CPP_DEBUG_CODE_(if (parser_return_code_ == PRC_SUCCESS) std::cerr << 
#line 165 "xrb_parse_datafile_parser.trison"
"DataFile::Parser" << (m_scanner->GetFiLoc().IsValid() ? " ("+m_scanner->GetFiLoc().AsString()+")" : g_empty_string) << ":"
#line 381 "xrb_parse_datafile_parser.cpp"
 << " Parse() is returning PRC_SUCCESS" << std::endl)
    TRISON_CPP_DEBUG_CODE_(if (parser_return_code_ == PRC_UNHANDLED_PARSE_ERROR) std::cerr << 
#line 165 "xrb_parse_datafile_parser.trison"
"DataFile::Parser" << (m_scanner->GetFiLoc().IsValid() ? " ("+m_scanner->GetFiLoc().AsString()+")" : g_empty_string) << ":"
#line 386 "xrb_parse_datafile_parser.cpp"
 << " Parse() is returning PRC_UNHANDLED_PARSE_ERROR" << std::endl)

    return parser_return_code_;
}

void Parser::ThrowAwayToken_ (Token::Data &token_data) throw()
{
    TRISON_CPP_DEBUG_CODE_(std::cerr << 
#line 165 "xrb_parse_datafile_parser.trison"
"DataFile::Parser" << (m_scanner->GetFiLoc().IsValid() ? " ("+m_scanner->GetFiLoc().AsString()+")" : g_empty_string) << ":"
#line 397 "xrb_parse_datafile_parser.cpp"
 << " executing throw-away-token actions" << std::endl)


#line 155 "xrb_parse_datafile_parser.trison"

    Delete(token_data);

#line 405 "xrb_parse_datafile_parser.cpp"
}

Parser::Token Parser::Scan_ () throw()
{

#line 158 "xrb_parse_datafile_parser.trison"

    ASSERT1(m_scanner != NULL);
    return m_scanner->Scan();

#line 416 "xrb_parse_datafile_parser.cpp"
}

void Parser::ClearStack_ () throw()
{
    if (m_stack_.empty())
        return; // nothing to do

    TRISON_CPP_DEBUG_CODE_(std::cerr << 
#line 165 "xrb_parse_datafile_parser.trison"
"DataFile::Parser" << (m_scanner->GetFiLoc().IsValid() ? " ("+m_scanner->GetFiLoc().AsString()+")" : g_empty_string) << ":"
#line 427 "xrb_parse_datafile_parser.cpp"
 << " clearing the stack" << std::endl)

    Stack_::iterator it = m_stack_.begin();
    Stack_::iterator it_end = m_stack_.end();
    // skip the bottom of the stack, since it
    // contains the start state and no token data.
    ++it;
    for ( ; it != it_end; ++it)
        ThrowAwayToken_(it->m_token_data);
    m_stack_.clear();
}

void Parser::ClearLookaheadQueue_ () throw()
{
    TRISON_CPP_DEBUG_CODE_(std::cerr << 
#line 165 "xrb_parse_datafile_parser.trison"
"DataFile::Parser" << (m_scanner->GetFiLoc().IsValid() ? " ("+m_scanner->GetFiLoc().AsString()+")" : g_empty_string) << ":"
#line 445 "xrb_parse_datafile_parser.cpp"
 << " clearing the lookahead queue" << std::endl)

    for (LookaheadQueue_::iterator it = m_lookahead_queue_.begin(), it_end = m_lookahead_queue_.end(); it != it_end; ++it)
        ThrowAwayToken_(it->m_data);
    m_lookahead_queue_.clear();
}

Parser::Token const &Parser::Lookahead_ (LookaheadQueue_::size_type index) throw()
{
    while (index >= m_lookahead_queue_.size())
    {
        m_lookahead_queue_.push_back(Scan_());

        TRISON_CPP_DEBUG_CODE_(std::cerr << 
#line 165 "xrb_parse_datafile_parser.trison"
"DataFile::Parser" << (m_scanner->GetFiLoc().IsValid() ? " ("+m_scanner->GetFiLoc().AsString()+")" : g_empty_string) << ":"
#line 462 "xrb_parse_datafile_parser.cpp"
 << " pushed " << *m_lookahead_queue_.rbegin() << " onto back of lookahead queue" << std::endl)
    }
    return m_lookahead_queue_[index];
}

bool Parser::ExerciseTransition_ (Transition_ const &transition)
{
    switch (transition.m_type)
    {
        case Transition_::REDUCE:
        {
            // execute the indicated reduction rule, push the returned Token
            // onto the front of the lookahead queue, then pop the corresponding
            // number of stack elements.
            assert(transition.m_data < ms_rule_count_);
            Rule_ const &rule = ms_rule_table_[transition.m_data];
            TRISON_CPP_DEBUG_CODE_(std::cerr << 
#line 165 "xrb_parse_datafile_parser.trison"
"DataFile::Parser" << (m_scanner->GetFiLoc().IsValid() ? " ("+m_scanner->GetFiLoc().AsString()+")" : g_empty_string) << ":"
#line 482 "xrb_parse_datafile_parser.cpp"
 << " REDUCE " << rule.m_description << std::endl)
            assert(m_stack_.size() > rule.m_token_count);
            m_lookahead_queue_.push_front(
                Token(
                    rule.m_reduction_nonterminal_token_id,
                    ExecuteReductionRule_(transition.m_data)));
            m_stack_.resize(m_stack_.size() - rule.m_token_count);
            assert(rule.m_reduction_nonterminal_token_id < ms_token_name_count_);
            TRISON_CPP_DEBUG_CODE_(std::cerr << 
#line 165 "xrb_parse_datafile_parser.trison"
"DataFile::Parser" << (m_scanner->GetFiLoc().IsValid() ? " ("+m_scanner->GetFiLoc().AsString()+")" : g_empty_string) << ":"
#line 494 "xrb_parse_datafile_parser.cpp"
 << " pushed " << Token(rule.m_reduction_nonterminal_token_id) << " onto front of lookahead queue" << std::endl)
            return false; // indicating the parser isn't returning
        }

        case Transition_::RETURN:
            TRISON_CPP_DEBUG_CODE_(std::cerr << 
#line 165 "xrb_parse_datafile_parser.trison"
"DataFile::Parser" << (m_scanner->GetFiLoc().IsValid() ? " ("+m_scanner->GetFiLoc().AsString()+")" : g_empty_string) << ":"
#line 503 "xrb_parse_datafile_parser.cpp"
 << " RETURN" << std::endl)
            return true; // indicating the parser is returning

        case Transition_::SHIFT:
            // push the state (indicated by the shift transition) and token data
            // onto the stack, then pop the corresponding lookahead.
            assert(transition.m_data < ms_state_count_);
            assert(Lookahead_(0).m_id < ms_token_name_count_); // at this point, we're past a possible
                                                               // client error, so asserting here is ok.
            TRISON_CPP_DEBUG_CODE_(std::cerr << 
#line 165 "xrb_parse_datafile_parser.trison"
"DataFile::Parser" << (m_scanner->GetFiLoc().IsValid() ? " ("+m_scanner->GetFiLoc().AsString()+")" : g_empty_string) << ":"
#line 516 "xrb_parse_datafile_parser.cpp"
 << " SHIFT " << Lookahead_(0) << std::endl)
            m_stack_.push_back(StackElement_(transition.m_data, Lookahead_(0).m_data));
            m_lookahead_queue_.pop_front();
            return false; // indicating the parser isn't returning

        case Transition_::ERROR_PANIC:
            TRISON_CPP_DEBUG_CODE_(std::cerr << 
#line 165 "xrb_parse_datafile_parser.trison"
"DataFile::Parser" << (m_scanner->GetFiLoc().IsValid() ? " ("+m_scanner->GetFiLoc().AsString()+")" : g_empty_string) << ":"
#line 526 "xrb_parse_datafile_parser.cpp"
 << " ERROR_PANIC" << std::endl)
            m_is_in_error_panic_ = true;
            return false; // indicating the parser isn't returning

        default:
            assert(false && "invalid transition type (bad state machine, or memory corruption)");
            return false; // indicating the parser isn't returning
    }
}

Parser::Token::Data Parser::ExecuteReductionRule_ (BarfCpp_::Uint32 const rule_index_) throw()
{
    assert(rule_index_ < ms_rule_count_);
    TRISON_CPP_DEBUG_CODE_(std::cerr << 
#line 165 "xrb_parse_datafile_parser.trison"
"DataFile::Parser" << (m_scanner->GetFiLoc().IsValid() ? " ("+m_scanner->GetFiLoc().AsString()+")" : g_empty_string) << ":"
#line 543 "xrb_parse_datafile_parser.cpp"
 << " executing reduction rule " << rule_index_ << std::endl)
    switch (rule_index_)
    {
        default:
            assert(false && "this should never happen");
            return NULL;

        case 0:
        {
            assert(ms_rule_table_[rule_index_].m_token_count < m_stack_.size());
            Structure * element_list(DStaticCast<Structure *>(m_stack_[m_stack_.size()-1].m_token_data));

#line 186 "xrb_parse_datafile_parser.trison"

        ASSERT1(element_list != NULL);
        return element_list;
    
#line 561 "xrb_parse_datafile_parser.cpp"
            break;
        }

        case 1:
        {
            assert(ms_rule_table_[rule_index_].m_token_count < m_stack_.size());

#line 192 "xrb_parse_datafile_parser.trison"

        EmitError("general syntax error", FL);
        return new Structure();
    
#line 574 "xrb_parse_datafile_parser.cpp"
            break;
        }

        case 2:
        {
            assert(ms_rule_table_[rule_index_].m_token_count < m_stack_.size());
            Structure * element_list(DStaticCast<Structure *>(m_stack_[m_stack_.size()-2].m_token_data));
            KeyPair * element(DStaticCast<KeyPair *>(m_stack_[m_stack_.size()-1].m_token_data));

#line 201 "xrb_parse_datafile_parser.trison"

        ASSERT1(element_list != NULL);

        if (element != NULL)
        {
            try
            {
                element_list->AddKeyPair(element);
            }
            catch (std::string const &exception)
            {
                EmitError(exception, FL);
                Delete(element);
            }
        }
        return element_list;
    
#line 602 "xrb_parse_datafile_parser.cpp"
            break;
        }

        case 3:
        {
            assert(ms_rule_table_[rule_index_].m_token_count < m_stack_.size());

#line 220 "xrb_parse_datafile_parser.trison"

        return new Structure();
    
#line 614 "xrb_parse_datafile_parser.cpp"
            break;
        }

        case 4:
        {
            assert(ms_rule_table_[rule_index_].m_token_count < m_stack_.size());
            String * key(DStaticCast<String *>(m_stack_[m_stack_.size()-3].m_token_data));
            Value * value(DStaticCast<Value *>(m_stack_[m_stack_.size()-2].m_token_data));

#line 228 "xrb_parse_datafile_parser.trison"

        ASSERT1(key != NULL);
        if (value == NULL)
        {
            Delete(key);
            return NULL;
        }

        KeyPair *key_pair = new KeyPair(key->Get(), value);
        Delete(key);
        return key_pair;
    
#line 637 "xrb_parse_datafile_parser.cpp"
            break;
        }

        case 5:
        {
            assert(ms_rule_table_[rule_index_].m_token_count < m_stack_.size());
            String * key(DStaticCast<String *>(m_stack_[m_stack_.size()-3].m_token_data));

#line 242 "xrb_parse_datafile_parser.trison"

        ASSERT1(key != NULL);
        std::ostringstream out;
        out << "syntax error in element with key \"" << key->Get() << "\"";
        EmitError(out.str(), FL);
        Delete(key);
        return NULL;
    
#line 655 "xrb_parse_datafile_parser.cpp"
            break;
        }

        case 6:
        {
            assert(ms_rule_table_[rule_index_].m_token_count < m_stack_.size());

#line 252 "xrb_parse_datafile_parser.trison"

        EmitError("syntax error in element", FL);
        return NULL;
    
#line 668 "xrb_parse_datafile_parser.cpp"
            break;
        }

        case 7:
        {
            assert(ms_rule_table_[rule_index_].m_token_count < m_stack_.size());
            Structure * element_list(DStaticCast<Structure *>(m_stack_[m_stack_.size()-2].m_token_data));

#line 261 "xrb_parse_datafile_parser.trison"

        ASSERT1(element_list != NULL);
        return element_list;
    
#line 682 "xrb_parse_datafile_parser.cpp"
            break;
        }

        case 8:
        {
            assert(ms_rule_table_[rule_index_].m_token_count < m_stack_.size());

#line 267 "xrb_parse_datafile_parser.trison"

        EmitError("syntax error in structure", FL);
        return new Structure();
    
#line 695 "xrb_parse_datafile_parser.cpp"
            break;
        }

        case 9:
        {
            assert(ms_rule_table_[rule_index_].m_token_count < m_stack_.size());
            Array * value_list(DStaticCast<Array *>(m_stack_[m_stack_.size()-2].m_token_data));

#line 276 "xrb_parse_datafile_parser.trison"

        ASSERT1(value_list != NULL);
        return value_list;
    
#line 709 "xrb_parse_datafile_parser.cpp"
            break;
        }

        case 10:
        {
            assert(ms_rule_table_[rule_index_].m_token_count < m_stack_.size());
            Array * value_list(DStaticCast<Array *>(m_stack_[m_stack_.size()-3].m_token_data));

#line 282 "xrb_parse_datafile_parser.trison"

        ASSERT1(value_list != NULL);
        return value_list;
    
#line 723 "xrb_parse_datafile_parser.cpp"
            break;
        }

        case 11:
        {
            assert(ms_rule_table_[rule_index_].m_token_count < m_stack_.size());

#line 288 "xrb_parse_datafile_parser.trison"

        return new Array();
    
#line 735 "xrb_parse_datafile_parser.cpp"
            break;
        }

        case 12:
        {
            assert(ms_rule_table_[rule_index_].m_token_count < m_stack_.size());

#line 293 "xrb_parse_datafile_parser.trison"

        EmitError("syntax error in array", FL);
        return NULL;
    
#line 748 "xrb_parse_datafile_parser.cpp"
            break;
        }

        case 13:
        {
            assert(ms_rule_table_[rule_index_].m_token_count < m_stack_.size());
            Array * value_list(DStaticCast<Array *>(m_stack_[m_stack_.size()-3].m_token_data));
            Value * value(DStaticCast<Value *>(m_stack_[m_stack_.size()-1].m_token_data));

#line 302 "xrb_parse_datafile_parser.trison"

        ASSERT1(value_list != NULL);
        if (value != NULL)
        {
            try
            {
                value_list->AppendValue(value);
            }
            catch (std::string const &exception)
            {
                EmitError(exception, FL);
                Delete(value);
            }
        }
        return value_list;
    
#line 775 "xrb_parse_datafile_parser.cpp"
            break;
        }

        case 14:
        {
            assert(ms_rule_table_[rule_index_].m_token_count < m_stack_.size());
            Value * value(DStaticCast<Value *>(m_stack_[m_stack_.size()-1].m_token_data));

#line 320 "xrb_parse_datafile_parser.trison"

        Array *value_list = new Array();
        if (value != NULL)
        {
            try
            {
                value_list->AppendValue(value);
            }
            catch (std::string const &)
            {
                ASSERT1(false && "this should never happen");
                Delete(value);
            }
        }
        return value_list;
    
#line 801 "xrb_parse_datafile_parser.cpp"
            break;
        }

        case 15:
        {
            assert(ms_rule_table_[rule_index_].m_token_count < m_stack_.size());
            Boolean * value(DStaticCast<Boolean *>(m_stack_[m_stack_.size()-1].m_token_data));

#line 340 "xrb_parse_datafile_parser.trison"
 return value; 
#line 812 "xrb_parse_datafile_parser.cpp"
            break;
        }

        case 16:
        {
            assert(ms_rule_table_[rule_index_].m_token_count < m_stack_.size());
            SignedInteger * value(DStaticCast<SignedInteger *>(m_stack_[m_stack_.size()-1].m_token_data));

#line 341 "xrb_parse_datafile_parser.trison"
 return value; 
#line 823 "xrb_parse_datafile_parser.cpp"
            break;
        }

        case 17:
        {
            assert(ms_rule_table_[rule_index_].m_token_count < m_stack_.size());
            UnsignedInteger * value(DStaticCast<UnsignedInteger *>(m_stack_[m_stack_.size()-1].m_token_data));

#line 342 "xrb_parse_datafile_parser.trison"
 return value; 
#line 834 "xrb_parse_datafile_parser.cpp"
            break;
        }

        case 18:
        {
            assert(ms_rule_table_[rule_index_].m_token_count < m_stack_.size());
            Floaty * value(DStaticCast<Floaty *>(m_stack_[m_stack_.size()-1].m_token_data));

#line 343 "xrb_parse_datafile_parser.trison"
 return value; 
#line 845 "xrb_parse_datafile_parser.cpp"
            break;
        }

        case 19:
        {
            assert(ms_rule_table_[rule_index_].m_token_count < m_stack_.size());
            Character * value(DStaticCast<Character *>(m_stack_[m_stack_.size()-1].m_token_data));

#line 344 "xrb_parse_datafile_parser.trison"
 return value; 
#line 856 "xrb_parse_datafile_parser.cpp"
            break;
        }

        case 20:
        {
            assert(ms_rule_table_[rule_index_].m_token_count < m_stack_.size());
            String * value(DStaticCast<String *>(m_stack_[m_stack_.size()-1].m_token_data));

#line 345 "xrb_parse_datafile_parser.trison"
 return value; 
#line 867 "xrb_parse_datafile_parser.cpp"
            break;
        }

        case 21:
        {
            assert(ms_rule_table_[rule_index_].m_token_count < m_stack_.size());
            Structure * value(DStaticCast<Structure *>(m_stack_[m_stack_.size()-1].m_token_data));

#line 346 "xrb_parse_datafile_parser.trison"
 return value; 
#line 878 "xrb_parse_datafile_parser.cpp"
            break;
        }

        case 22:
        {
            assert(ms_rule_table_[rule_index_].m_token_count < m_stack_.size());
            Array * value(DStaticCast<Array *>(m_stack_[m_stack_.size()-1].m_token_data));

#line 347 "xrb_parse_datafile_parser.trison"
 return value; 
#line 889 "xrb_parse_datafile_parser.cpp"
            break;
        }

        case 23:
        {
            assert(ms_rule_table_[rule_index_].m_token_count < m_stack_.size());
            String * string(DStaticCast<String *>(m_stack_[m_stack_.size()-3].m_token_data));
            String * string_fragment(DStaticCast<String *>(m_stack_[m_stack_.size()-1].m_token_data));

#line 356 "xrb_parse_datafile_parser.trison"

        ASSERT1(string != NULL);
        ASSERT1(string_fragment != NULL);
        string->AppendString(string_fragment->Get());
        Delete(string_fragment);
        return string;
    
#line 907 "xrb_parse_datafile_parser.cpp"
            break;
        }

        case 24:
        {
            assert(ms_rule_table_[rule_index_].m_token_count < m_stack_.size());
            String * string_fragment(DStaticCast<String *>(m_stack_[m_stack_.size()-1].m_token_data));

#line 365 "xrb_parse_datafile_parser.trison"

        ASSERT1(string_fragment != NULL);
        return string_fragment;
    
#line 921 "xrb_parse_datafile_parser.cpp"
            break;
        }

        case 25:
        {
            assert(ms_rule_table_[rule_index_].m_token_count < m_stack_.size());
            String * string(DStaticCast<String *>(m_stack_[m_stack_.size()-2].m_token_data));
            String * string_fragment(DStaticCast<String *>(m_stack_[m_stack_.size()-1].m_token_data));

#line 371 "xrb_parse_datafile_parser.trison"

        ASSERT1(string != NULL);
        ASSERT1(string_fragment != NULL);
        string->AppendString(string_fragment->Get());
        Delete(string_fragment);
        EmitError("use + to concatenate strings (or did you forget a comma?)", FL);
        return string;
    
#line 940 "xrb_parse_datafile_parser.cpp"
            break;
        }

    }

    assert(false && "no value returned from reduction rule code block");
    return NULL;
}

void Parser::PrintParserStatus_ (std::ostream &stream) const
{
    assert(!m_stack_.empty());

    stream << 
#line 165 "xrb_parse_datafile_parser.trison"
"DataFile::Parser" << (m_scanner->GetFiLoc().IsValid() ? " ("+m_scanner->GetFiLoc().AsString()+")" : g_empty_string) << ":"
#line 957 "xrb_parse_datafile_parser.cpp"
 << " parser stack: ";
    for (Stack_::const_iterator it = m_stack_.begin(), it_end = m_stack_.end(); it != it_end; ++it)
    {
        stream << it->m_state_index;
        Stack_::const_iterator next_it = it;
        if (++next_it != it_end)
            stream << ' ';
    }
    stream << std::endl;

    PrintIndented_(stream, ms_state_table_[m_stack_.rbegin()->m_state_index].m_description);
    stream << std::endl;
}

void Parser::PrintIndented_ (std::ostream &stream, char const *string) const
{
    assert(string != NULL);
    stream << 
#line 165 "xrb_parse_datafile_parser.trison"
"DataFile::Parser" << (m_scanner->GetFiLoc().IsValid() ? " ("+m_scanner->GetFiLoc().AsString()+")" : g_empty_string) << ":"
#line 978 "xrb_parse_datafile_parser.cpp"
 << "    ";
    while (*string != '\0')
    {
        if (*string == '\n')
            stream << '\n' << 
#line 165 "xrb_parse_datafile_parser.trison"
"DataFile::Parser" << (m_scanner->GetFiLoc().IsValid() ? " ("+m_scanner->GetFiLoc().AsString()+")" : g_empty_string) << ":"
#line 986 "xrb_parse_datafile_parser.cpp"
 << "    ";
        else
            stream << *string;
        ++string;
    }
}

std::ostream &operator << (std::ostream &stream, Parser::Token const &token)
{
    if (token.m_id < Parser::ms_token_name_count_)
        stream << '(' << Parser::ms_token_name_table_[token.m_id] << ')';
    else
        stream << "!INVALID TOKEN!";
    return stream;
}

Parser::Rule_ const Parser::ms_rule_table_[] =
{
    { Parser::Nonterminal_::data_file, 1, "data_file <- element_list" },
    { Parser::Nonterminal_::data_file, 1, "data_file <- ERROR_" },
    { Parser::Nonterminal_::element_list, 2, "element_list <- element_list element" },
    { Parser::Nonterminal_::element_list, 0, "element_list <-" },
    { Parser::Nonterminal_::element, 3, "element <- IDENTIFIER value ';'" },
    { Parser::Nonterminal_::element, 3, "element <- IDENTIFIER ERROR_ ';'" },
    { Parser::Nonterminal_::element, 2, "element <- ERROR_ ';'" },
    { Parser::Nonterminal_::structure, 3, "structure <- '{' element_list '}'" },
    { Parser::Nonterminal_::structure, 3, "structure <- '{' ERROR_ '}'" },
    { Parser::Nonterminal_::array, 3, "array <- '[' value_list ']'" },
    { Parser::Nonterminal_::array, 4, "array <- '[' value_list ',' ']'" },
    { Parser::Nonterminal_::array, 2, "array <- '[' ']'" },
    { Parser::Nonterminal_::array, 3, "array <- '[' ERROR_ ']'" },
    { Parser::Nonterminal_::value_list, 3, "value_list <- value_list ',' value" },
    { Parser::Nonterminal_::value_list, 1, "value_list <- value" },
    { Parser::Nonterminal_::value, 1, "value <- BOOLEAN" },
    { Parser::Nonterminal_::value, 1, "value <- SINT32" },
    { Parser::Nonterminal_::value, 1, "value <- UINT32" },
    { Parser::Nonterminal_::value, 1, "value <- FLOATY" },
    { Parser::Nonterminal_::value, 1, "value <- CHARACTER" },
    { Parser::Nonterminal_::value, 1, "value <- string" },
    { Parser::Nonterminal_::value, 1, "value <- structure" },
    { Parser::Nonterminal_::value, 1, "value <- array" },
    { Parser::Nonterminal_::string, 3, "string <- string '+' STRING_FRAGMENT" },
    { Parser::Nonterminal_::string, 1, "string <- STRING_FRAGMENT" },
    { Parser::Nonterminal_::string, 2, "string <- string STRING_FRAGMENT" }
};
BarfCpp_::Size const Parser::ms_rule_count_ = sizeof(Parser::ms_rule_table_) / sizeof(*Parser::ms_rule_table_);

Parser::State_ const Parser::ms_state_table_[] =
{
    { 3, ms_transition_table_+0, "START data_file                               \nrule 0: data_file <- . element_list           \nrule 2: element_list <- . element_list element\nrule 3: element_list <- .                     \nrule 1: data_file <- . ERROR_                 " },
    { 2, ms_transition_table_+3, "rule 0: data_file <- . element_list           \nrule 2: element_list <- . element_list element\nrule 3: element_list <- .                     " },
    { 4, ms_transition_table_+5, "rule 0: data_file <- element_list .           \nrule 2: element_list <- element_list . element\nrule 4: element <- . IDENTIFIER value ';'     \nrule 5: element <- . IDENTIFIER ERROR_ ';'    \nrule 6: element <- . ERROR_ ';'               " },
    { 2, ms_transition_table_+9, "rule 6: element <- ERROR_ . ';'" },
    { 1, ms_transition_table_+11, "rule 6: element <- ERROR_ ';' ." },
    { 14, ms_transition_table_+12, "rule 4: element <- IDENTIFIER . value ';'      \nrule 15: value <- . BOOLEAN                    \nrule 16: value <- . SINT32                     \nrule 17: value <- . UINT32                     \nrule 18: value <- . FLOATY                     \nrule 19: value <- . CHARACTER                  \nrule 20: value <- . string                     \nrule 23: string <- . string '+' STRING_FRAGMENT\nrule 24: string <- . STRING_FRAGMENT           \nrule 25: string <- . string STRING_FRAGMENT    \nrule 21: value <- . structure                  \nrule 7: structure <- . '{' element_list '}'    \nrule 8: structure <- . '{' ERROR_ '}'          \nrule 22: value <- . array                      \nrule 9: array <- . '[' value_list ']'          \nrule 10: array <- . '[' value_list ',' ']'     \nrule 11: array <- . '[' ']'                    \nrule 12: array <- . '[' ERROR_ ']'             \nrule 5: element <- IDENTIFIER . ERROR_ ';'     " },
    { 16, ms_transition_table_+26, "rule 15: value <- . BOOLEAN                    \nrule 16: value <- . SINT32                     \nrule 17: value <- . UINT32                     \nrule 18: value <- . FLOATY                     \nrule 19: value <- . CHARACTER                  \nrule 20: value <- . string                     \nrule 23: string <- . string '+' STRING_FRAGMENT\nrule 24: string <- . STRING_FRAGMENT           \nrule 25: string <- . string STRING_FRAGMENT    \nrule 21: value <- . structure                  \nrule 7: structure <- . '{' element_list '}'    \nrule 8: structure <- . '{' ERROR_ '}'          \nrule 22: value <- . array                      \nrule 9: array <- . '[' value_list ']'          \nrule 9: array <- '[' . value_list ']'          \nrule 13: value_list <- . value_list ',' value  \nrule 14: value_list <- . value                 \nrule 10: array <- . '[' value_list ',' ']'     \nrule 10: array <- '[' . value_list ',' ']'     \nrule 11: array <- . '[' ']'                    \nrule 11: array <- '[' . ']'                    \nrule 12: array <- . '[' ERROR_ ']'             \nrule 12: array <- '[' . ERROR_ ']'             " },
    { 1, ms_transition_table_+42, "rule 11: array <- '[' ']' ." },
    { 2, ms_transition_table_+43, "rule 2: element_list <- . element_list element\nrule 7: structure <- '{' . element_list '}'   \nrule 8: structure <- '{' . ERROR_ '}'         \nrule 3: element_list <- .                     " },
    { 2, ms_transition_table_+45, "rule 2: element_list <- . element_list element\nrule 7: structure <- '{' . element_list '}'   \nrule 3: element_list <- .                     " },
    { 5, ms_transition_table_+47, "rule 2: element_list <- element_list . element\nrule 4: element <- . IDENTIFIER value ';'     \nrule 7: structure <- '{' element_list . '}'   \nrule 5: element <- . IDENTIFIER ERROR_ ';'    \nrule 6: element <- . ERROR_ ';'               " },
    { 1, ms_transition_table_+52, "rule 7: structure <- '{' element_list '}' ." },
    { 1, ms_transition_table_+53, "rule 2: element_list <- element_list element ." },
    { 2, ms_transition_table_+54, "rule 12: array <- '[' ERROR_ . ']'" },
    { 1, ms_transition_table_+56, "rule 12: array <- '[' ERROR_ ']' ." },
    { 1, ms_transition_table_+57, "rule 15: value <- BOOLEAN ." },
    { 1, ms_transition_table_+58, "rule 16: value <- SINT32 ." },
    { 1, ms_transition_table_+59, "rule 17: value <- UINT32 ." },
    { 1, ms_transition_table_+60, "rule 18: value <- FLOATY ." },
    { 1, ms_transition_table_+61, "rule 19: value <- CHARACTER ." },
    { 1, ms_transition_table_+62, "rule 24: string <- STRING_FRAGMENT ." },
    { 1, ms_transition_table_+63, "rule 21: value <- structure ." },
    { 1, ms_transition_table_+64, "rule 22: value <- array ." },
    { 3, ms_transition_table_+65, "rule 9: array <- '[' value_list . ']'        \nrule 13: value_list <- value_list . ',' value\nrule 10: array <- '[' value_list . ',' ']'   " },
    { 14, ms_transition_table_+68, "rule 15: value <- . BOOLEAN                    \nrule 16: value <- . SINT32                     \nrule 17: value <- . UINT32                     \nrule 18: value <- . FLOATY                     \nrule 19: value <- . CHARACTER                  \nrule 20: value <- . string                     \nrule 23: string <- . string '+' STRING_FRAGMENT\nrule 24: string <- . STRING_FRAGMENT           \nrule 25: string <- . string STRING_FRAGMENT    \nrule 21: value <- . structure                  \nrule 7: structure <- . '{' element_list '}'    \nrule 8: structure <- . '{' ERROR_ '}'          \nrule 22: value <- . array                      \nrule 9: array <- . '[' value_list ']'          \nrule 13: value_list <- value_list ',' . value  \nrule 10: array <- . '[' value_list ',' ']'     \nrule 10: array <- '[' value_list ',' . ']'     \nrule 11: array <- . '[' ']'                    \nrule 12: array <- . '[' ERROR_ ']'             " },
    { 1, ms_transition_table_+82, "rule 10: array <- '[' value_list ',' ']' ." },
    { 1, ms_transition_table_+83, "rule 13: value_list <- value_list ',' value ." },
    { 3, ms_transition_table_+84, "rule 20: value <- string .                     \nrule 23: string <- string . '+' STRING_FRAGMENT\nrule 25: string <- string . STRING_FRAGMENT    " },
    { 2, ms_transition_table_+87, "rule 23: string <- string '+' . STRING_FRAGMENT" },
    { 1, ms_transition_table_+89, "rule 23: string <- string '+' STRING_FRAGMENT ." },
    { 1, ms_transition_table_+90, "rule 25: string <- string STRING_FRAGMENT ." },
    { 1, ms_transition_table_+91, "rule 9: array <- '[' value_list ']' ." },
    { 1, ms_transition_table_+92, "rule 14: value_list <- value ." },
    { 2, ms_transition_table_+93, "rule 5: element <- IDENTIFIER ERROR_ . ';'" },
    { 1, ms_transition_table_+95, "rule 5: element <- IDENTIFIER ERROR_ ';' ." },
    { 2, ms_transition_table_+96, "rule 4: element <- IDENTIFIER value . ';'" },
    { 1, ms_transition_table_+98, "rule 4: element <- IDENTIFIER value ';' ." },
    { 1, ms_transition_table_+99, "RETURN data_file" },
    { 2, ms_transition_table_+100, "START element_list                            \nrule 2: element_list <- . element_list element\nrule 3: element_list <- .                     " },
    { 4, ms_transition_table_+102, "RETURN element_list                           \nrule 2: element_list <- element_list . element\nrule 4: element <- . IDENTIFIER value ';'     \nrule 5: element <- . IDENTIFIER ERROR_ ';'    \nrule 6: element <- . ERROR_ ';'               " },
    { 4, ms_transition_table_+106, "START element                             \nrule 4: element <- . IDENTIFIER value ';' \nrule 5: element <- . IDENTIFIER ERROR_ ';'\nrule 6: element <- . ERROR_ ';'           " },
    { 1, ms_transition_table_+110, "RETURN element" },
    { 3, ms_transition_table_+111, "START structure                            \nrule 7: structure <- . '{' element_list '}'\nrule 8: structure <- . '{' ERROR_ '}'      " },
    { 1, ms_transition_table_+114, "RETURN structure" },
    { 3, ms_transition_table_+115, "START array                               \nrule 9: array <- . '[' value_list ']'     \nrule 10: array <- . '[' value_list ',' ']'\nrule 11: array <- . '[' ']'               \nrule 12: array <- . '[' ERROR_ ']'        " },
    { 1, ms_transition_table_+118, "RETURN array" },
    { 14, ms_transition_table_+119, "rule 15: value <- . BOOLEAN                    \nrule 16: value <- . SINT32                     \nrule 17: value <- . UINT32                     \nrule 18: value <- . FLOATY                     \nrule 19: value <- . CHARACTER                  \nrule 20: value <- . string                     \nrule 23: string <- . string '+' STRING_FRAGMENT\nrule 24: string <- . STRING_FRAGMENT           \nrule 25: string <- . string STRING_FRAGMENT    \nrule 21: value <- . structure                  \nrule 7: structure <- . '{' element_list '}'    \nrule 8: structure <- . '{' ERROR_ '}'          \nrule 22: value <- . array                      \nrule 9: array <- . '[' value_list ']'          \nSTART value_list                               \nrule 13: value_list <- . value_list ',' value  \nrule 14: value_list <- . value                 \nrule 10: array <- . '[' value_list ',' ']'     \nrule 11: array <- . '[' ']'                    \nrule 12: array <- . '[' ERROR_ ']'             " },
    { 2, ms_transition_table_+133, "RETURN value_list                            \nrule 13: value_list <- value_list . ',' value" },
    { 13, ms_transition_table_+135, "rule 15: value <- . BOOLEAN                    \nrule 16: value <- . SINT32                     \nrule 17: value <- . UINT32                     \nrule 18: value <- . FLOATY                     \nrule 19: value <- . CHARACTER                  \nrule 20: value <- . string                     \nrule 23: string <- . string '+' STRING_FRAGMENT\nrule 24: string <- . STRING_FRAGMENT           \nrule 25: string <- . string STRING_FRAGMENT    \nrule 21: value <- . structure                  \nrule 7: structure <- . '{' element_list '}'    \nrule 8: structure <- . '{' ERROR_ '}'          \nrule 22: value <- . array                      \nrule 9: array <- . '[' value_list ']'          \nrule 13: value_list <- value_list ',' . value  \nrule 10: array <- . '[' value_list ',' ']'     \nrule 11: array <- . '[' ']'                    \nrule 12: array <- . '[' ERROR_ ']'             " },
    { 13, ms_transition_table_+148, "START value                                    \nrule 15: value <- . BOOLEAN                    \nrule 16: value <- . SINT32                     \nrule 17: value <- . UINT32                     \nrule 18: value <- . FLOATY                     \nrule 19: value <- . CHARACTER                  \nrule 20: value <- . string                     \nrule 23: string <- . string '+' STRING_FRAGMENT\nrule 24: string <- . STRING_FRAGMENT           \nrule 25: string <- . string STRING_FRAGMENT    \nrule 21: value <- . structure                  \nrule 7: structure <- . '{' element_list '}'    \nrule 8: structure <- . '{' ERROR_ '}'          \nrule 22: value <- . array                      \nrule 9: array <- . '[' value_list ']'          \nrule 10: array <- . '[' value_list ',' ']'     \nrule 11: array <- . '[' ']'                    \nrule 12: array <- . '[' ERROR_ ']'             " },
    { 1, ms_transition_table_+161, "RETURN value" },
    { 3, ms_transition_table_+162, "START string                                   \nrule 23: string <- . string '+' STRING_FRAGMENT\nrule 24: string <- . STRING_FRAGMENT           \nrule 25: string <- . string STRING_FRAGMENT    " },
    { 3, ms_transition_table_+165, "RETURN string                                  \nrule 23: string <- string . '+' STRING_FRAGMENT\nrule 25: string <- string . STRING_FRAGMENT    " }
};
BarfCpp_::Size const Parser::ms_state_count_ = sizeof(Parser::ms_state_table_) / sizeof(*Parser::ms_state_table_);

Parser::Transition_ const Parser::ms_transition_table_[] =
{
    { Parser::Transition_::REDUCE, 3, 0, ms_lookahead_table_+0 },
    { Parser::Transition_::SHIFT, 37, 1, ms_lookahead_table_+0 },
    { Parser::Transition_::SHIFT, 2, 1, ms_lookahead_table_+1 },
    { Parser::Transition_::REDUCE, 3, 0, ms_lookahead_table_+2 },
    { Parser::Transition_::SHIFT, 2, 1, ms_lookahead_table_+2 },
    { Parser::Transition_::REDUCE, 0, 0, ms_lookahead_table_+3 },
    { Parser::Transition_::SHIFT, 3, 1, ms_lookahead_table_+3 },
    { Parser::Transition_::SHIFT, 5, 1, ms_lookahead_table_+4 },
    { Parser::Transition_::SHIFT, 12, 1, ms_lookahead_table_+5 },
    { Parser::Transition_::ERROR_PANIC, 0, 0, ms_lookahead_table_+6 },
    { Parser::Transition_::SHIFT, 4, 1, ms_lookahead_table_+6 },
    { Parser::Transition_::REDUCE, 6, 0, ms_lookahead_table_+7 },
    { Parser::Transition_::ERROR_PANIC, 0, 0, ms_lookahead_table_+7 },
    { Parser::Transition_::SHIFT, 6, 1, ms_lookahead_table_+7 },
    { Parser::Transition_::SHIFT, 8, 1, ms_lookahead_table_+8 },
    { Parser::Transition_::SHIFT, 33, 1, ms_lookahead_table_+9 },
    { Parser::Transition_::SHIFT, 15, 1, ms_lookahead_table_+10 },
    { Parser::Transition_::SHIFT, 16, 1, ms_lookahead_table_+11 },
    { Parser::Transition_::SHIFT, 17, 1, ms_lookahead_table_+12 },
    { Parser::Transition_::SHIFT, 18, 1, ms_lookahead_table_+13 },
    { Parser::Transition_::SHIFT, 19, 1, ms_lookahead_table_+14 },
    { Parser::Transition_::SHIFT, 20, 1, ms_lookahead_table_+15 },
    { Parser::Transition_::SHIFT, 21, 1, ms_lookahead_table_+16 },
    { Parser::Transition_::SHIFT, 22, 1, ms_lookahead_table_+17 },
    { Parser::Transition_::SHIFT, 35, 1, ms_lookahead_table_+18 },
    { Parser::Transition_::SHIFT, 27, 1, ms_lookahead_table_+19 },
    { Parser::Transition_::ERROR_PANIC, 0, 0, ms_lookahead_table_+20 },
    { Parser::Transition_::SHIFT, 6, 1, ms_lookahead_table_+20 },
    { Parser::Transition_::SHIFT, 7, 1, ms_lookahead_table_+21 },
    { Parser::Transition_::SHIFT, 8, 1, ms_lookahead_table_+22 },
    { Parser::Transition_::SHIFT, 13, 1, ms_lookahead_table_+23 },
    { Parser::Transition_::SHIFT, 15, 1, ms_lookahead_table_+24 },
    { Parser::Transition_::SHIFT, 16, 1, ms_lookahead_table_+25 },
    { Parser::Transition_::SHIFT, 17, 1, ms_lookahead_table_+26 },
    { Parser::Transition_::SHIFT, 18, 1, ms_lookahead_table_+27 },
    { Parser::Transition_::SHIFT, 19, 1, ms_lookahead_table_+28 },
    { Parser::Transition_::SHIFT, 20, 1, ms_lookahead_table_+29 },
    { Parser::Transition_::SHIFT, 21, 1, ms_lookahead_table_+30 },
    { Parser::Transition_::SHIFT, 22, 1, ms_lookahead_table_+31 },
    { Parser::Transition_::SHIFT, 23, 1, ms_lookahead_table_+32 },
    { Parser::Transition_::SHIFT, 32, 1, ms_lookahead_table_+33 },
    { Parser::Transition_::SHIFT, 27, 1, ms_lookahead_table_+34 },
    { Parser::Transition_::REDUCE, 11, 0, ms_lookahead_table_+35 },
    { Parser::Transition_::REDUCE, 3, 0, ms_lookahead_table_+35 },
    { Parser::Transition_::SHIFT, 10, 1, ms_lookahead_table_+35 },
    { Parser::Transition_::REDUCE, 3, 0, ms_lookahead_table_+36 },
    { Parser::Transition_::SHIFT, 10, 1, ms_lookahead_table_+36 },
    { Parser::Transition_::ERROR_PANIC, 0, 0, ms_lookahead_table_+37 },
    { Parser::Transition_::SHIFT, 11, 1, ms_lookahead_table_+37 },
    { Parser::Transition_::SHIFT, 3, 1, ms_lookahead_table_+38 },
    { Parser::Transition_::SHIFT, 5, 1, ms_lookahead_table_+39 },
    { Parser::Transition_::SHIFT, 12, 1, ms_lookahead_table_+40 },
    { Parser::Transition_::REDUCE, 7, 0, ms_lookahead_table_+41 },
    { Parser::Transition_::REDUCE, 2, 0, ms_lookahead_table_+41 },
    { Parser::Transition_::ERROR_PANIC, 0, 0, ms_lookahead_table_+41 },
    { Parser::Transition_::SHIFT, 14, 1, ms_lookahead_table_+41 },
    { Parser::Transition_::REDUCE, 12, 0, ms_lookahead_table_+42 },
    { Parser::Transition_::REDUCE, 15, 0, ms_lookahead_table_+42 },
    { Parser::Transition_::REDUCE, 16, 0, ms_lookahead_table_+42 },
    { Parser::Transition_::REDUCE, 17, 0, ms_lookahead_table_+42 },
    { Parser::Transition_::REDUCE, 18, 0, ms_lookahead_table_+42 },
    { Parser::Transition_::REDUCE, 19, 0, ms_lookahead_table_+42 },
    { Parser::Transition_::REDUCE, 24, 0, ms_lookahead_table_+42 },
    { Parser::Transition_::REDUCE, 21, 0, ms_lookahead_table_+42 },
    { Parser::Transition_::REDUCE, 22, 0, ms_lookahead_table_+42 },
    { Parser::Transition_::ERROR_PANIC, 0, 0, ms_lookahead_table_+42 },
    { Parser::Transition_::SHIFT, 24, 1, ms_lookahead_table_+42 },
    { Parser::Transition_::SHIFT, 31, 1, ms_lookahead_table_+43 },
    { Parser::Transition_::ERROR_PANIC, 0, 0, ms_lookahead_table_+44 },
    { Parser::Transition_::SHIFT, 6, 1, ms_lookahead_table_+44 },
    { Parser::Transition_::SHIFT, 25, 1, ms_lookahead_table_+45 },
    { Parser::Transition_::SHIFT, 8, 1, ms_lookahead_table_+46 },
    { Parser::Transition_::SHIFT, 15, 1, ms_lookahead_table_+47 },
    { Parser::Transition_::SHIFT, 16, 1, ms_lookahead_table_+48 },
    { Parser::Transition_::SHIFT, 17, 1, ms_lookahead_table_+49 },
    { Parser::Transition_::SHIFT, 18, 1, ms_lookahead_table_+50 },
    { Parser::Transition_::SHIFT, 19, 1, ms_lookahead_table_+51 },
    { Parser::Transition_::SHIFT, 20, 1, ms_lookahead_table_+52 },
    { Parser::Transition_::SHIFT, 21, 1, ms_lookahead_table_+53 },
    { Parser::Transition_::SHIFT, 22, 1, ms_lookahead_table_+54 },
    { Parser::Transition_::SHIFT, 26, 1, ms_lookahead_table_+55 },
    { Parser::Transition_::SHIFT, 27, 1, ms_lookahead_table_+56 },
    { Parser::Transition_::REDUCE, 10, 0, ms_lookahead_table_+57 },
    { Parser::Transition_::REDUCE, 13, 0, ms_lookahead_table_+57 },
    { Parser::Transition_::REDUCE, 20, 0, ms_lookahead_table_+57 },
    { Parser::Transition_::SHIFT, 28, 1, ms_lookahead_table_+57 },
    { Parser::Transition_::SHIFT, 30, 1, ms_lookahead_table_+58 },
    { Parser::Transition_::ERROR_PANIC, 0, 0, ms_lookahead_table_+59 },
    { Parser::Transition_::SHIFT, 29, 1, ms_lookahead_table_+59 },
    { Parser::Transition_::REDUCE, 23, 0, ms_lookahead_table_+60 },
    { Parser::Transition_::REDUCE, 25, 0, ms_lookahead_table_+60 },
    { Parser::Transition_::REDUCE, 9, 0, ms_lookahead_table_+60 },
    { Parser::Transition_::REDUCE, 14, 0, ms_lookahead_table_+60 },
    { Parser::Transition_::ERROR_PANIC, 0, 0, ms_lookahead_table_+60 },
    { Parser::Transition_::SHIFT, 34, 1, ms_lookahead_table_+60 },
    { Parser::Transition_::REDUCE, 5, 0, ms_lookahead_table_+61 },
    { Parser::Transition_::ERROR_PANIC, 0, 0, ms_lookahead_table_+61 },
    { Parser::Transition_::SHIFT, 36, 1, ms_lookahead_table_+61 },
    { Parser::Transition_::REDUCE, 4, 0, ms_lookahead_table_+62 },
    { Parser::Transition_::RETURN, 0, 0, ms_lookahead_table_+62 },
    { Parser::Transition_::REDUCE, 3, 0, ms_lookahead_table_+62 },
    { Parser::Transition_::SHIFT, 39, 1, ms_lookahead_table_+62 },
    { Parser::Transition_::RETURN, 0, 0, ms_lookahead_table_+63 },
    { Parser::Transition_::SHIFT, 3, 1, ms_lookahead_table_+63 },
    { Parser::Transition_::SHIFT, 5, 1, ms_lookahead_table_+64 },
    { Parser::Transition_::SHIFT, 12, 1, ms_lookahead_table_+65 },
    { Parser::Transition_::ERROR_PANIC, 0, 0, ms_lookahead_table_+66 },
    { Parser::Transition_::SHIFT, 3, 1, ms_lookahead_table_+66 },
    { Parser::Transition_::SHIFT, 5, 1, ms_lookahead_table_+67 },
    { Parser::Transition_::SHIFT, 41, 1, ms_lookahead_table_+68 },
    { Parser::Transition_::RETURN, 0, 0, ms_lookahead_table_+69 },
    { Parser::Transition_::ERROR_PANIC, 0, 0, ms_lookahead_table_+69 },
    { Parser::Transition_::SHIFT, 8, 1, ms_lookahead_table_+69 },
    { Parser::Transition_::SHIFT, 43, 1, ms_lookahead_table_+70 },
    { Parser::Transition_::RETURN, 0, 0, ms_lookahead_table_+71 },
    { Parser::Transition_::ERROR_PANIC, 0, 0, ms_lookahead_table_+71 },
    { Parser::Transition_::SHIFT, 6, 1, ms_lookahead_table_+71 },
    { Parser::Transition_::SHIFT, 45, 1, ms_lookahead_table_+72 },
    { Parser::Transition_::RETURN, 0, 0, ms_lookahead_table_+73 },
    { Parser::Transition_::ERROR_PANIC, 0, 0, ms_lookahead_table_+73 },
    { Parser::Transition_::SHIFT, 6, 1, ms_lookahead_table_+73 },
    { Parser::Transition_::SHIFT, 8, 1, ms_lookahead_table_+74 },
    { Parser::Transition_::SHIFT, 15, 1, ms_lookahead_table_+75 },
    { Parser::Transition_::SHIFT, 16, 1, ms_lookahead_table_+76 },
    { Parser::Transition_::SHIFT, 17, 1, ms_lookahead_table_+77 },
    { Parser::Transition_::SHIFT, 18, 1, ms_lookahead_table_+78 },
    { Parser::Transition_::SHIFT, 19, 1, ms_lookahead_table_+79 },
    { Parser::Transition_::SHIFT, 20, 1, ms_lookahead_table_+80 },
    { Parser::Transition_::SHIFT, 21, 1, ms_lookahead_table_+81 },
    { Parser::Transition_::SHIFT, 22, 1, ms_lookahead_table_+82 },
    { Parser::Transition_::SHIFT, 47, 1, ms_lookahead_table_+83 },
    { Parser::Transition_::SHIFT, 32, 1, ms_lookahead_table_+84 },
    { Parser::Transition_::SHIFT, 27, 1, ms_lookahead_table_+85 },
    { Parser::Transition_::RETURN, 0, 0, ms_lookahead_table_+86 },
    { Parser::Transition_::SHIFT, 48, 1, ms_lookahead_table_+86 },
    { Parser::Transition_::ERROR_PANIC, 0, 0, ms_lookahead_table_+87 },
    { Parser::Transition_::SHIFT, 6, 1, ms_lookahead_table_+87 },
    { Parser::Transition_::SHIFT, 8, 1, ms_lookahead_table_+88 },
    { Parser::Transition_::SHIFT, 15, 1, ms_lookahead_table_+89 },
    { Parser::Transition_::SHIFT, 16, 1, ms_lookahead_table_+90 },
    { Parser::Transition_::SHIFT, 17, 1, ms_lookahead_table_+91 },
    { Parser::Transition_::SHIFT, 18, 1, ms_lookahead_table_+92 },
    { Parser::Transition_::SHIFT, 19, 1, ms_lookahead_table_+93 },
    { Parser::Transition_::SHIFT, 20, 1, ms_lookahead_table_+94 },
    { Parser::Transition_::SHIFT, 21, 1, ms_lookahead_table_+95 },
    { Parser::Transition_::SHIFT, 22, 1, ms_lookahead_table_+96 },
    { Parser::Transition_::SHIFT, 26, 1, ms_lookahead_table_+97 },
    { Parser::Transition_::SHIFT, 27, 1, ms_lookahead_table_+98 },
    { Parser::Transition_::ERROR_PANIC, 0, 0, ms_lookahead_table_+99 },
    { Parser::Transition_::SHIFT, 6, 1, ms_lookahead_table_+99 },
    { Parser::Transition_::SHIFT, 8, 1, ms_lookahead_table_+100 },
    { Parser::Transition_::SHIFT, 15, 1, ms_lookahead_table_+101 },
    { Parser::Transition_::SHIFT, 16, 1, ms_lookahead_table_+102 },
    { Parser::Transition_::SHIFT, 17, 1, ms_lookahead_table_+103 },
    { Parser::Transition_::SHIFT, 18, 1, ms_lookahead_table_+104 },
    { Parser::Transition_::SHIFT, 19, 1, ms_lookahead_table_+105 },
    { Parser::Transition_::SHIFT, 20, 1, ms_lookahead_table_+106 },
    { Parser::Transition_::SHIFT, 21, 1, ms_lookahead_table_+107 },
    { Parser::Transition_::SHIFT, 22, 1, ms_lookahead_table_+108 },
    { Parser::Transition_::SHIFT, 50, 1, ms_lookahead_table_+109 },
    { Parser::Transition_::SHIFT, 27, 1, ms_lookahead_table_+110 },
    { Parser::Transition_::RETURN, 0, 0, ms_lookahead_table_+111 },
    { Parser::Transition_::ERROR_PANIC, 0, 0, ms_lookahead_table_+111 },
    { Parser::Transition_::SHIFT, 20, 1, ms_lookahead_table_+111 },
    { Parser::Transition_::SHIFT, 52, 1, ms_lookahead_table_+112 },
    { Parser::Transition_::RETURN, 0, 0, ms_lookahead_table_+113 },
    { Parser::Transition_::SHIFT, 28, 1, ms_lookahead_table_+113 },
    { Parser::Transition_::SHIFT, 30, 1, ms_lookahead_table_+114 }
};
BarfCpp_::Size const Parser::ms_transition_count_ = sizeof(Parser::ms_transition_table_) / sizeof(*Parser::ms_transition_table_);

Parser::Token::Id const Parser::ms_lookahead_table_[] =
{
    Parser::Nonterminal_::data_file,
    Parser::Nonterminal_::element_list,
    Parser::Nonterminal_::element_list,
    Parser::Terminal::ERROR_,
    Parser::Terminal::IDENTIFIER,
    Parser::Nonterminal_::element,
    ';',
    '[',
    '{',
    Parser::Terminal::ERROR_,
    Parser::Terminal::BOOLEAN,
    Parser::Terminal::SINT32,
    Parser::Terminal::UINT32,
    Parser::Terminal::FLOATY,
    Parser::Terminal::CHARACTER,
    Parser::Terminal::STRING_FRAGMENT,
    Parser::Nonterminal_::structure,
    Parser::Nonterminal_::array,
    Parser::Nonterminal_::value,
    Parser::Nonterminal_::string,
    '[',
    ']',
    '{',
    Parser::Terminal::ERROR_,
    Parser::Terminal::BOOLEAN,
    Parser::Terminal::SINT32,
    Parser::Terminal::UINT32,
    Parser::Terminal::FLOATY,
    Parser::Terminal::CHARACTER,
    Parser::Terminal::STRING_FRAGMENT,
    Parser::Nonterminal_::structure,
    Parser::Nonterminal_::array,
    Parser::Nonterminal_::value_list,
    Parser::Nonterminal_::value,
    Parser::Nonterminal_::string,
    Parser::Nonterminal_::element_list,
    Parser::Nonterminal_::element_list,
    '}',
    Parser::Terminal::ERROR_,
    Parser::Terminal::IDENTIFIER,
    Parser::Nonterminal_::element,
    ']',
    ',',
    ']',
    '[',
    ']',
    '{',
    Parser::Terminal::BOOLEAN,
    Parser::Terminal::SINT32,
    Parser::Terminal::UINT32,
    Parser::Terminal::FLOATY,
    Parser::Terminal::CHARACTER,
    Parser::Terminal::STRING_FRAGMENT,
    Parser::Nonterminal_::structure,
    Parser::Nonterminal_::array,
    Parser::Nonterminal_::value,
    Parser::Nonterminal_::string,
    '+',
    Parser::Terminal::STRING_FRAGMENT,
    Parser::Terminal::STRING_FRAGMENT,
    ';',
    ';',
    Parser::Nonterminal_::element_list,
    Parser::Terminal::ERROR_,
    Parser::Terminal::IDENTIFIER,
    Parser::Nonterminal_::element,
    Parser::Terminal::ERROR_,
    Parser::Terminal::IDENTIFIER,
    Parser::Nonterminal_::element,
    '{',
    Parser::Nonterminal_::structure,
    '[',
    Parser::Nonterminal_::array,
    '[',
    '{',
    Parser::Terminal::BOOLEAN,
    Parser::Terminal::SINT32,
    Parser::Terminal::UINT32,
    Parser::Terminal::FLOATY,
    Parser::Terminal::CHARACTER,
    Parser::Terminal::STRING_FRAGMENT,
    Parser::Nonterminal_::structure,
    Parser::Nonterminal_::array,
    Parser::Nonterminal_::value_list,
    Parser::Nonterminal_::value,
    Parser::Nonterminal_::string,
    ',',
    '[',
    '{',
    Parser::Terminal::BOOLEAN,
    Parser::Terminal::SINT32,
    Parser::Terminal::UINT32,
    Parser::Terminal::FLOATY,
    Parser::Terminal::CHARACTER,
    Parser::Terminal::STRING_FRAGMENT,
    Parser::Nonterminal_::structure,
    Parser::Nonterminal_::array,
    Parser::Nonterminal_::value,
    Parser::Nonterminal_::string,
    '[',
    '{',
    Parser::Terminal::BOOLEAN,
    Parser::Terminal::SINT32,
    Parser::Terminal::UINT32,
    Parser::Terminal::FLOATY,
    Parser::Terminal::CHARACTER,
    Parser::Terminal::STRING_FRAGMENT,
    Parser::Nonterminal_::structure,
    Parser::Nonterminal_::array,
    Parser::Nonterminal_::value,
    Parser::Nonterminal_::string,
    Parser::Terminal::STRING_FRAGMENT,
    Parser::Nonterminal_::string,
    '+',
    Parser::Terminal::STRING_FRAGMENT
};
BarfCpp_::Size const Parser::ms_lookahead_count_ = sizeof(Parser::ms_lookahead_table_) / sizeof(*Parser::ms_lookahead_table_);

char const *const Parser::ms_token_name_table_[] =
{
    "'\\0'",
    "'\\x01'",
    "'\\x02'",
    "'\\x03'",
    "'\\x04'",
    "'\\x05'",
    "'\\x06'",
    "'\\a'",
    "'\\b'",
    "'\\t'",
    "'\\n'",
    "'\\v'",
    "'\\f'",
    "'\\r'",
    "'\\x0E'",
    "'\\x0F'",
    "'\\x10'",
    "'\\x11'",
    "'\\x12'",
    "'\\x13'",
    "'\\x14'",
    "'\\x15'",
    "'\\x16'",
    "'\\x17'",
    "'\\x18'",
    "'\\x19'",
    "'\\x1A'",
    "'\\x1B'",
    "'\\x1C'",
    "'\\x1D'",
    "'\\x1E'",
    "'\\x1F'",
    "' '",
    "'!'",
    "'\"'",
    "'#'",
    "'$'",
    "'%'",
    "'&'",
    "'\\''",
    "'('",
    "')'",
    "'*'",
    "'+'",
    "','",
    "'-'",
    "'.'",
    "'/'",
    "'0'",
    "'1'",
    "'2'",
    "'3'",
    "'4'",
    "'5'",
    "'6'",
    "'7'",
    "'8'",
    "'9'",
    "':'",
    "';'",
    "'<'",
    "'='",
    "'>'",
    "'?'",
    "'@'",
    "'A'",
    "'B'",
    "'C'",
    "'D'",
    "'E'",
    "'F'",
    "'G'",
    "'H'",
    "'I'",
    "'J'",
    "'K'",
    "'L'",
    "'M'",
    "'N'",
    "'O'",
    "'P'",
    "'Q'",
    "'R'",
    "'S'",
    "'T'",
    "'U'",
    "'V'",
    "'W'",
    "'X'",
    "'Y'",
    "'Z'",
    "'['",
    "'\\\\'",
    "']'",
    "'^'",
    "'_'",
    "'`'",
    "'a'",
    "'b'",
    "'c'",
    "'d'",
    "'e'",
    "'f'",
    "'g'",
    "'h'",
    "'i'",
    "'j'",
    "'k'",
    "'l'",
    "'m'",
    "'n'",
    "'o'",
    "'p'",
    "'q'",
    "'r'",
    "'s'",
    "'t'",
    "'u'",
    "'v'",
    "'w'",
    "'x'",
    "'y'",
    "'z'",
    "'{'",
    "'|'",
    "'}'",
    "'~'",
    "'\\x7F'",
    "'\\x80'",
    "'\\x81'",
    "'\\x82'",
    "'\\x83'",
    "'\\x84'",
    "'\\x85'",
    "'\\x86'",
    "'\\x87'",
    "'\\x88'",
    "'\\x89'",
    "'\\x8A'",
    "'\\x8B'",
    "'\\x8C'",
    "'\\x8D'",
    "'\\x8E'",
    "'\\x8F'",
    "'\\x90'",
    "'\\x91'",
    "'\\x92'",
    "'\\x93'",
    "'\\x94'",
    "'\\x95'",
    "'\\x96'",
    "'\\x97'",
    "'\\x98'",
    "'\\x99'",
    "'\\x9A'",
    "'\\x9B'",
    "'\\x9C'",
    "'\\x9D'",
    "'\\x9E'",
    "'\\x9F'",
    "'\\xA0'",
    "'\\xA1'",
    "'\\xA2'",
    "'\\xA3'",
    "'\\xA4'",
    "'\\xA5'",
    "'\\xA6'",
    "'\\xA7'",
    "'\\xA8'",
    "'\\xA9'",
    "'\\xAA'",
    "'\\xAB'",
    "'\\xAC'",
    "'\\xAD'",
    "'\\xAE'",
    "'\\xAF'",
    "'\\xB0'",
    "'\\xB1'",
    "'\\xB2'",
    "'\\xB3'",
    "'\\xB4'",
    "'\\xB5'",
    "'\\xB6'",
    "'\\xB7'",
    "'\\xB8'",
    "'\\xB9'",
    "'\\xBA'",
    "'\\xBB'",
    "'\\xBC'",
    "'\\xBD'",
    "'\\xBE'",
    "'\\xBF'",
    "'\\xC0'",
    "'\\xC1'",
    "'\\xC2'",
    "'\\xC3'",
    "'\\xC4'",
    "'\\xC5'",
    "'\\xC6'",
    "'\\xC7'",
    "'\\xC8'",
    "'\\xC9'",
    "'\\xCA'",
    "'\\xCB'",
    "'\\xCC'",
    "'\\xCD'",
    "'\\xCE'",
    "'\\xCF'",
    "'\\xD0'",
    "'\\xD1'",
    "'\\xD2'",
    "'\\xD3'",
    "'\\xD4'",
    "'\\xD5'",
    "'\\xD6'",
    "'\\xD7'",
    "'\\xD8'",
    "'\\xD9'",
    "'\\xDA'",
    "'\\xDB'",
    "'\\xDC'",
    "'\\xDD'",
    "'\\xDE'",
    "'\\xDF'",
    "'\\xE0'",
    "'\\xE1'",
    "'\\xE2'",
    "'\\xE3'",
    "'\\xE4'",
    "'\\xE5'",
    "'\\xE6'",
    "'\\xE7'",
    "'\\xE8'",
    "'\\xE9'",
    "'\\xEA'",
    "'\\xEB'",
    "'\\xEC'",
    "'\\xED'",
    "'\\xEE'",
    "'\\xEF'",
    "'\\xF0'",
    "'\\xF1'",
    "'\\xF2'",
    "'\\xF3'",
    "'\\xF4'",
    "'\\xF5'",
    "'\\xF6'",
    "'\\xF7'",
    "'\\xF8'",
    "'\\xF9'",
    "'\\xFA'",
    "'\\xFB'",
    "'\\xFC'",
    "'\\xFD'",
    "'\\xFE'",
    "'\\xFF'",
    "END_",
    "ERROR_",
    "BAD_TOKEN",
    "BOOLEAN",
    "SINT32",
    "UINT32",
    "FLOATY",
    "CHARACTER",
    "STRING_FRAGMENT",
    "IDENTIFIER",
    "data_file",
    "element_list",
    "element",
    "structure",
    "array",
    "value_list",
    "value",
    "string"
};
BarfCpp_::Size const Parser::ms_token_name_count_ = sizeof(Parser::ms_token_name_table_) / sizeof(*Parser::ms_token_name_table_);

// ///////////////////////////////////////////////////////////////////////
// end of internal trison-generated parser guts
// ///////////////////////////////////////////////////////////////////////


#line 145 "xrb_parse_datafile_parser.trison"

} // end of namespace DataFile
} // end of namespace Parse
} // end of namespace Xrb

#line 1675 "xrb_parse_datafile_parser.cpp"
