// ///////////////////////////////////////////////////////////////////////////
// xrb_compiletimeasserts.cpp by Victor Dods, created 2006/04/16
// ///////////////////////////////////////////////////////////////////////////
// Unless a different license was explicitly granted in writing by the
// copyright holder (Victor Dods), this software is freely distributable under
// the terms of the GNU General Public License, version 2.  Any works deriving
// from this work must also be released under the GNU GPL.  See the included
// file LICENSE for details.
// ///////////////////////////////////////////////////////////////////////////

#include "xrb.hpp"

#include "xrb_key.hpp"

namespace Xrb
{

GLOBAL_SCOPE_COMPILE_TIME_ASSERT(SIZEOF_CHAR_CHECK, sizeof(char) == 1)
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(SIZEOF_SINT8_CHECK, sizeof(Sint8) == 1)
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(SIZEOF_UINT8_CHECK, sizeof(Uint8) == 1)
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(SIZEOF_SINT16_CHECK, sizeof(Sint16) == 2)
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(SIZEOF_UINT16_CHECK, sizeof(Uint16) == 2)
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(SIZEOF_SINT32_CHECK, sizeof(Sint32) == 4)
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(SIZEOF_UINT32_CHECK, sizeof(Uint32) == 4)
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(SIZEOF_FLOAT_CHECK, sizeof(float) == 4)
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(SIZEOF_DOUBLE_CHECK, sizeof(double) == 8)

GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_TAB_IS_ASCII, Key::TAB == '\t')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_RETURN_IS_ASCII, Key::RETURN == '\r')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_ESCAPE_IS_ASCII, Key::ESCAPE == 0x1B)
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_SPACE_IS_ASCII, Key::SPACE == ' ')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_QUOTE_IS_ASCII, Key::QUOTE == '\'')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_COMMA_IS_ASCII, Key::COMMA == ',')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_MINUS_IS_ASCII, Key::MINUS == '-')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_PERIOD_IS_ASCII, Key::PERIOD == '.')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_SLASH_IS_ASCII, Key::SLASH == '/')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_ZERO_IS_ASCII, Key::ZERO == '0')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_ONE_IS_ASCII, Key::ONE == '1')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_TWO_IS_ASCII, Key::TWO == '2')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_THREE_IS_ASCII, Key::THREE == '3')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_FOUR_IS_ASCII, Key::FOUR == '4')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_FIVE_IS_ASCII, Key::FIVE == '5')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_SIX_IS_ASCII, Key::SIX == '6')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_SEVEN_IS_ASCII, Key::SEVEN == '7')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_EIGHT_IS_ASCII, Key::EIGHT == '8')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_NINE_IS_ASCII, Key::NINE == '9')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_SEMICOLON_IS_ASCII, Key::SEMICOLON == ';')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_EQUALS_IS_ASCII, Key::EQUALS == '=')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_LEFTBRACKET_IS_ASCII, Key::LEFTBRACKET == '[')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_BACKSLASH_IS_ASCII, Key::BACKSLASH == '\\')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_RIGHTBRACKET_IS_ASCII, Key::RIGHTBRACKET == ']')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_BACKQUOTE_IS_ASCII, Key::BACKQUOTE == '`')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_A_IS_ASCII, Key::A == 'a')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_B_IS_ASCII, Key::B == 'b')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_C_IS_ASCII, Key::C == 'c')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_D_IS_ASCII, Key::D == 'd')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_E_IS_ASCII, Key::E == 'e')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_F_IS_ASCII, Key::F == 'f')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_G_IS_ASCII, Key::G == 'g')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_H_IS_ASCII, Key::H == 'h')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_I_IS_ASCII, Key::I == 'i')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_J_IS_ASCII, Key::J == 'j')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_K_IS_ASCII, Key::K == 'k')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_L_IS_ASCII, Key::L == 'l')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_M_IS_ASCII, Key::M == 'm')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_N_IS_ASCII, Key::N == 'n')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_O_IS_ASCII, Key::O == 'o')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_P_IS_ASCII, Key::P == 'p')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_Q_IS_ASCII, Key::Q == 'q')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_R_IS_ASCII, Key::R == 'r')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_S_IS_ASCII, Key::S == 's')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_T_IS_ASCII, Key::T == 't')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_U_IS_ASCII, Key::U == 'u')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_V_IS_ASCII, Key::V == 'v')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_W_IS_ASCII, Key::W == 'w')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_X_IS_ASCII, Key::X == 'x')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_Y_IS_ASCII, Key::Y == 'y')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_Z_IS_ASCII, Key::Z == 'z')
GLOBAL_SCOPE_COMPILE_TIME_ASSERT(KEY_DELETE_IS_ASCII, Key::DELETE == 0x7F)

} // end of namespace Xrb
